### ISSUE TITLE
Empty component-descriptor will not be overwtitten

### ISSUE THREAD

**Issue by guewa** [gardener/component-cli#14]
**What happened**:
When trying to add to an existing empty component-descriptr, e.g.
`component-cli component-archive sources add test/component-archive --archive "test-archive" --component-name "example.com/component/name" --component-version "v0.0.1"`
an error comes up
`unable to parse component archive from test/component-archive: unable to parse component descriptor read from component-descriptor.yaml: component.name: Does not match pattern '^[a-z0-9.\-]+[.][a-z]{2,4}/[-a-z0-9/_.]*$';component.version: Does not match pattern '^[v]?(0|[1-9]\d*)(?:\.(0|[1-9]\d*))?(?:\.(0|[1-9]\d*))?(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'`

existing file was:
```
cat test/component-archive/component-descriptor.yaml 
component:
  componentReferences: []
  name: ""
  provider: internal
  repositoryContexts: []
  resources: []
  sources: []
  version: ""
meta:
  schemaVersion: v2
```

**What you expected to happen**:
document-descriptor should be overwritten
**How to reproduce it (as minimally and precisely as possible)**:
create fiel mentioned above and run command
**Anything else we need to know**:

**Environment**:
