### ISSUE TITLE
Improve validating error message

### ISSUE THREAD

**Issue by schrodit** [gardener/component-cli#46]
**What would you like to be added**:
When a component descriptor with a invalid name is created, the error message is misleading `unable to parse ref: invalid reference format`

Example invalid descriptor:
```
meta:
  schemaVersion: v2

component:
  name: https://example.com/my-component
  version: 0.0.1
``` 

We should first validate the component descriptor. Especially the name and version that is used for the oci reference calculation
